name: Daily Landslide Prediction

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true        # <-- FORZA IL DOWNLOAD DEL FILE GPKG REALE!
          fetch-depth: 1   # <-- Scarica solo l'ultima versione per fare prima

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Prediction Script
        env:
          EE_PRIVATE_KEY: ${{ secrets.EE_PRIVATE_KEY }}
        run: |
          python daily_prediction.py

      - name: Commit and Push new map
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily_maps/
          git commit -m "Automated prediction map update" || echo "No changes to commit"
          git push
